name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: kcarrasc0
          outputs: |
            dist/ocean.gif?color_snake=#00bfff&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist
